import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import { SiteBackground } from "@/components/ui/background-components";
import "./globals.css";

const ppMondwest = localFont({
  src: "./fonts/PPMondwest-Regular.otf",
  variable: "--font-mondwest",
  weight: "400",
  display: "swap",
});

const ft88 = localFont({
  src: "./fonts/FT88-Regular.otf",
  variable: "--font-ft88",
  weight: "400",
  display: "swap",
});

const ft88School = localFont({
  src: "./fonts/FT88-School.otf",
  variable: "--font-ft88-school",
  weight: "400",
  display: "swap",
});

const ppNeueBit = localFont({
  src: "./fonts/PPNeueBit-Bold.otf",
  variable: "--font-neuebit",
  weight: "700",
  display: "swap",
});

const urbanist = localFont({
  src: [
    {
      path: "./fonts/Urbanist-VariableFont_wght.ttf",
      style: "normal",
    },
    {
      path: "./fonts/Urbanist-Italic-VariableFont_wght.ttf",
      style: "italic",
    },
  ],
  variable: "--font-urbanist",
  weight: "100 900",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shamita's Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/p-l.png",
    shortcut: "/p-l.png",
    apple: "/p-l.png",
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${ft88.variable} ${ft88School.variable} ${ppNeueBit.variable} ${urbanist.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SiteBackground>{children}</SiteBackground>
      </body>
    </html>
  );
}
